version: '3'

services:
  database-facilita:
    image: postgres
    restart: unless-stopped
    container_name: 'database-facilita'
    environment:
      - POSTGRES_DB=facilita-database
      - POSTGRES_USER=facilita-admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
    volumes:
      - ./database/data:/var/lib/postgresql/data